plugins {
    id 'com.android.application'
    id 'Orca-core'
    id 'kotlin-android'
    id 'Orca-compiler'
}

android {
    compileSdk 31
    namespace "com.orcinus.orca"
    defaultConfig {
        applicationId "com.orcinus.orca"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }


    Orca.go {
        isDebug = true
        signature = "-2103629870"
        encryptMode = "des"
        isBuildKotlin = false
        cacheValue = true
        instrumentalList = []

        applicationWhiteList =[
                "com.example.test.NextApplication","com.example.test.MyApplication"
        ]
        checkClass = [
            "com.example.test.MyApplication" : "onCreate"
        ]
        storeSet {
            "base" {
                value "222222"
            }
            "base2" {
                value "91239812931291"
            }
            "base3" {
                value "ksajdpjfopak[pwskdopasodpapo"
            }
            "base4" {
                value "htttps://wwww.google.com.hk"
            }
        }
    }

    signingConfigs {
        release {
            storeFile file("./app_test.jks")
            storePassword "123456"
            keyAlias "key0"
            keyPassword "123456"
        }
    }

    buildTypes {
        debug{
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'org.lsposed.hiddenapibypass:hiddenapibypass:+'
    //implementation project(":test_library")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.2")
    implementation project(":orca-annotation")
   // implementation project(":apkvertify")
    // implementation("com.github.ShowMeThe.Orca:orca-annotation:2.3.0")
}
